apiVersion: v2
name: grafana-agent
description: 'Grafana Agent'
type: application
version: 0.37.0
appVersion: 'v0.40.3'
dependencies:
  - name: kube-state-metrics
    version: "5.18.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled